### ISSUE TITLE
Find a bug in ReadAnnotationSetRefList

### ISSUE THREAD

**Issue by LoyieKing** [sailro/Dexer#10]
[annotation_set_ref_item format](https://source.android.com/devices/tech/dalvik/dex-format.html#set-ref-item) says 

> offset from the start of the file to the referenced annotation set or **0** if there are no annotations for this element.

https://github.com/sailro/Dexer/blob/master/Dexer/IO/DexReader.cs#L285-L286
```C#
    var size = reader.ReadUInt32();
    for (uint i = 0; i < size; i++)
    {
        var offset = reader.ReadUInt32();
        result.Add(ReadAnnotationSet(reader, offset));
    }
```
there should be
```C#
    for (uint i = 0; i < size; i++)
    {
        var offset = reader.ReadUInt();
        if (offset == 0)
            result.Add(new List<Annotation>(0));
        else
            result.Add(ReadAnnotationSet(offset));
    }
```

**Comment by sailro** [comment]
Good catch! Thank you
