### ISSUE TITLE
Fix InstructionWriter.WriteTo if exrta data present

### ISSUE THREAD

**Issue by naviHaRpY** [sailro/Dexer#12]
Hi!
Thanks for your wonderful framework. 
I found the little bug in **InstructionWriter.WriteTo**(BinaryWriter writer) method. 
https://github.com/sailro/Dexer/blob/7842c037642dbcc3149bd504db1d1dfe517ca20e/Dexer/IO/InstructionWriter.cs#L49

If extra data present, then their offset must be **alignment to 4-bytes**.
But if the **value of stats.CodeUnits is not even**, size of **Codes** array may be not sufficient to write the last element (fill-array-data processing).
My fix way:

```
			int cusz = stats.CodeUnits;
			if (stats.ExtraCodeUnits > 0) 
			{
				if (cusz % 2 != 0) cusz++;
			}
			_extraOffset = cusz;
			Codes = new ushort[cusz + stats.ExtraCodeUnits]; //fix array size
..... skip more code ...
		if (_extraOffset != cusz + stats.ExtraCodeUnits)
				throw new MalformedException("Data pointer out of range");
```

**Comment by sailro** [comment]
Thanks for your feedback!

Do you have a dex file showing the issue? This way we can fix and add the file to the test framework.

**Comment by naviHaRpY** [comment]
Example (see attach X-Plore 4.27.63): method  **a8.s0::\<clinit\>() : Void**
Try append to body method one **Nop**, or delete **Nop** after **ReturnVoid**
**Note: check value of stats.CodeUnits - must be not even.**
Try write method:
WriteTo -> WriteArrayData -> WriteInt ->System.IndexOutOfRangeException (for last element of last set "fill-array-data")
![Test](https://user-images.githubusercontent.com/89347012/130362423-b4358e35-eacb-48a1-ba79-a55e02b4b2ac.png)
[classes.zip](https://github.com/sailro/Dexer/files/7027693/classes.zip)

**Comment by naviHaRpY** [comment]
Method name has be broken by Editor:
**a8.s0::\<clinit\>() : Void**
