### ISSUE TITLE
What is a proper way to add NEW method?

### ISSUE THREAD

**Issue by CybIam** [sailro/Dexer#15]
Hello!

I am trying to create a new DEX file from scratch but failing to add class and method implementation.
What is a proper way to do it?
I am getting `KeyNotFoundException` either in TypeLookup or MethodLookup collection.
The proper(?) key in each collection exists.

Thanks!

**Comment by sailro** [comment]
Something like this:

```csharp
		var dex = new Dex();

		var cref = new ClassReference("fullname");
		dex.Import(cref);

		var returntype = PrimitiveType.Void;
		dex.Import(returntype);

		var parameterType = PrimitiveType.Int;
		var parameter = new Parameter(parameterType);
		dex.Import(parameterType);

		Prototype prototype = new Prototype(returntype, parameter);
		var mref = new MethodReference(cref, "methodname", prototype);
		dex.Import(mref);

		dex.Write("output.dex");
```

When you start from scratch, or when you need to add new stuff, you have to make sure all the types you plan to use are properly imported in the system.

**Comment by CybIam** [comment]
@sailro, thanks for fast response!

a bit of clarification - I need to write down method instructions.

ps
Of course I added all references (classes, fields, methods) so all lookup collections have them. Either I do something wrong (order wise) or there might be some bug with objects comparison.

**Comment by CybIam** [comment]
Figred it out.
I added class and method references wrong way. When implementing new class or method one should add reference to `*Definition` class not `*Reference`.

Thanks!
