### ISSUE TITLE
InstructionReader.ExtractSparseSwitch Fails to extract switch.

### ISSUE THREAD

**Issue by ghost** [sailro/Dexer#8]
The following exception is given:

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Dexer.IO.InstructionReader.<>c__DisplayClass49_1.<ExtractSparseSwitch>b__0() in C:\Users\david\.paket\git\db\Dexer\Dexer\IO\InstructionReader.cs:line 594
```

The following Java was used to generate this:

```
    public void sparseSwitch() {
        int success = 511;

        switch (success) {
            case 500:
                System.out.println("No result");
                break;
            case 300:
                System.out.println("Final result: Fail");
                break;
            case 1:
                System.out.println("Final result: Success");
                break;
            case 63335:
                System.out.println("crap");
                break;
            default:
                System.out.println("Unknown result");
                break;
        }
    }
```

**Comment by sailro** [comment]
Working on my side. Are you using something like proguard for obfuscation ?

**Comment by sailro** [comment]
Seems good on my side:

![image](https://cloud.githubusercontent.com/assets/638167/17570211/5ce7702c-5f00-11e6-9133-5d250e2e7f86.png)

All switch values are here, and if the value is not found the control flow will go to the "unknown result". I don't know if proguard can obfuscate the thing in a way that we are unable to decode the sparse switch data.

**Comment by ghost** [comment]
I haven't been able to reproduce this using the latest code, so I am going to close this for now, if I can find a solid reproduction I will reopen this issue
