### ISSUE TITLE
Please optimize these codes

### ISSUE THREAD

**Issue by LoyieKing** [sailro/Dexer#9]
Google's [Dalvik Exec Format Page](https://source.android.com/devices/tech/dalvik/dex-format.html#file-layout) clearly states that string_ids are sorted by lexicographical order.

> string identifiers list. These are identifiers for all the strings used by this file, either for internal naming (e.g., type descriptors) or as constant objects referred to by code. **This list must be sorted by string contents, using UTF-16 code point values** (not in a locale-sensitive manner), and it must not contain any duplicate entries.

As well as type_ids,field_ids,method_ids,class_defs and so on.

But actually, I found very ungly code, which is used  to find existed ClassDefinition and TypeReference in Dexer.

https://github.com/sailro/Dexer/blob/master/Dexer/Core/Dex.cs#L133-L162

    internal ClassDefinition GetClass(string fullname, List<ClassDefinition> container)
    {
        foreach (var item in container)
        {
            if (fullname.Equals(item.Fullname))
                return item;

            var inner = GetClass(fullname, item.InnerClasses);
            if (inner != null)
                return inner;
        }
        return null;
    }

    internal TypeReference Import(TypeReference tref, bool add)
    {
        foreach (var item in TypeReferences)
        {
            if (tref.Equals(item))
            {
                return item;
            }
        }
        if (add)
        {
            // if !add see TypeDescriptor comment 
            TypeReferences.Add(tref);
        }
        return tref;
    }

These places can obviously be optimized by using binary search.

**Comment by sailro** [comment]
You are right, but only when reading a stable file. When you start to add types/methods this rule is not valid anymore. Everything is correctly sorted (which is a costly operation) only when saving the final file to disk.

**Comment by LoyieKing** [comment]
> You are right, but only when reading a stable file. When you start to add types/methods this rule is not valid anymore. Everything is correctly sorted (which is a costly operation) only when saving the final file to disk.

So I think  there should be a brand new ListClass that can save loaded data and added data separately, because the added data is always a small amount
Or these References should be saved in Dictonary rather than List

**Comment by sailro** [comment]
Indeed
